camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: h2
    authorization:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    password:
  jersey:
    application-path: /rest
  security:
    oauth2:
      client:
        provider:
          okta:
            user-name-attribute: email

logging:
  level:
    com.antoinecampbell: debug
com:
  antoinecampbell:
    camunda:
      enable-internal-services: false

okta:
  oauth2:
    client-id: PALCEHOLDER
    client-secret: PLACEHOLDER
    issuer: PLACEHOLDER
    post-logout-redirect-uri: /
    redirect-uri: /authorization-code/callback
    scopes:
      - profile
      - email
      - openid
      - groups
---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: camunda

camunda:
  bpm:
    database:
      type: postgres

