camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: h2
spring:
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    password:
  jersey:
    application-path: /rest


logging:
  level:
    com.antoinecampbell: debug
com:
  antoinecampbell:
    camunda:
      enable-internal-services: true
---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: camunda

camunda:
  bpm:
    database:
      type: postgres

