camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
spring:
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    password:
    driver-class-name: org.h2.Driver
  jersey:
    application-path: /rest

logging:
  level:
    com.antoinecampbell: debug
---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: camunda

camunda:
  bpm:
    database:
      type: postgres

