camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: h2
    authorization:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    password:
  jersey:
    application-path: /rest
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: PLACEHOLDER
            client-secret: PLACEHOLDER
            redirect-uri: http://localhost:8080/login/oauth2/code/azure

logging:
  level:
    com.antoinecampbell: debug
com:
  antoinecampbell:
    camunda:
      enable-internal-services: true

azure:
  activedirectory:
    tenant-id: PLACEHOLDER
    active-directory-groups: camunda-admin
#    user-group:
#      allowed-groups: camunda-admin

---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: camunda

camunda:
  bpm:
    database:
      type: postgres

